### ISSUE TITLE
Global navigation bar disappears / changes color on secondary pages

### ISSUE THREAD

**Issue by narogers** [theiaconf/monochrome-pro#14]
The global navigation, which is correct on the home page, changes when moving deeper into the site. Something appears to be replacing or overriding the color settings which should be consistent across the entire site.

![Screenshot 2021-10-29 at 12-31-34 IAC Information Architecture conference – IAC Information Architecture conference](https://user-images.githubusercontent.com/1493179/139478658-001c3a17-1c1b-4918-aeed-0ca884778182.png)

![Screenshot 2021-10-29 at 12-31-52 Present at IAC](https://user-images.githubusercontent.com/1493179/139478670-0312be2f-6a9a-4f93-b0c8-da66da527d54.png)

**Comment by thenups** [comment]
taken care of in universal-nav PR
