### ISSUE TITLE
Add another option for headshots

### ISSUE THREAD

**Issue by narogers** [theiaconf/monochrome-pro#6]
Allow headshots to either be left aligned (default) or centered with the inclusion of a second class (.presenter_list_centered)

![Screen Shot 2021-10-08 at 4 33 27 PM](https://user-images.githubusercontent.com/1493179/136627315-84324b7c-2d96-4901-ba22-b437325e7fae.png)

![Screen Shot 2021-10-08 at 4 33 42 PM](https://user-images.githubusercontent.com/1493179/136627326-8731c11d-3a28-4f75-ad53-4787c1363dbc.png)

**Comment by Chonathon** [comment]
it would be a big job but the speaker section should probably be using a grid layout. maybe we should experiment with some of those prebuilt cards @narogers was looking at?

**Comment by narogers** [comment]
@Chonathon If you can alter the CSS to use a grid instead of flex have a go at it

**Comment by Chonathon** [comment]
There's some overlapping rules here that I'm still trying to account for to create the new class. It might be easier to just create a new class for the home page presenter list instead.

`.session-workshop_presenters,
.presenter_list {
  display: flex;
	flex-flow: row wrap;
	justify-content: center;
	align-items: center;
	margin-top: 1em;
}

.session-workshop_presenter,
.presenter_list .presenter {
	display: flex;
	margin-right: 2em;
}

.presenter_list .presenter {
	flex-flow: column nowrap;
	justify-content: center;
	align-items: center;
}

.session-workshop_presenter img,
.presenter_list .presenter_headshot {
	height: 3em;
	width: auto;
	margin-right: 0.5em;
}

.presenter .presenter-name a {
	text-decoration: none;
}`

**Comment by Chonathon** [comment]
#351
.img-circle {
    overflow: hidden;
    max-width: 140px;
    max-height: 140px;
    margin: 1em;
}


.presenter_list_left {
	
	display: grid;
	grid-template-columns: repeat(4, 1fr);
	grid-gap: 1em;
    
       
}

.presenter {
	display: flex;
	flex-flow: column;
	align-items: center;
	#
	margin: 1em;
}
